list1=["apple","grape","cherry"]
print(list1)
a=type(list1)
print(a)
print(list1[0])
print(list1[1])
print(list1[2])
list1[1]="banana"
print(list1[1])
for x in list1:
    print(x)
list1.insert(1,"tea")
print(list1)
list1.remove("cherry")
print(list1)
list1.pop()
print(list1)
list1.clear()
print(list1)